name = "Strata"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/digitalcraftsman/hugo-strata-theme/blob/master/LICENSE.md"
description = "A responsive and minimal single-page portfolio with blogging capabilities."
homepage = "//github.com/digitalcraftsman/hugo-strata-theme"
tags = ["contact form", "google analytics", "customizable", "single-page"]
features = []
min_version = "0.45"

[author]
  name = "Lars Pontoppidan"
  homepage = "//larsee.com"

# If porting an existing theme
[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
